### ISSUE TITLE
Messed up desktop icon

### ISSUE THREAD

**Issue by julianfairfax** [somepaulo/MoreWaita#10]
It seems your theme messes up the desktop icon. This is the file picker of an app (Signal in this case)

![image](https://user-images.githubusercontent.com/43753131/196205240-00f5a740-5d70-48da-81bb-06ac695a7cc3.png)

**Comment by somepaulo** [comment]
Judging by the screenshot the file picker here is not scaling the `.svg` to size, apparently expecting a sized `.png` rather than a scalable `.svg`.
I can see this in some apps and another discrepancy in others where the icon is scaled in the file-picker, but looks different from the other ones, while some other apps display everything alright.
I'll look into this.

**Comment by somepaulo** [comment]
This is now fixed by removing custom desktop icon and reverting back to Adwaita's original folder icons.
