### ISSUE TITLE
Icon request: Minetest (soon to be Luanti)

### ISSUE THREAD

**Issue by linfindel** [somepaulo/MoreWaita#115]
### Name of app

Minetest (soon to be Luanti)

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/a/a4/Minetest_logo.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

net.minetest.Minetest

### Optional image of the app icon

![Minetest_logo svg](https://github.com/somepaulo/MoreWaita/assets/116459177/6dad7753-b58d-4bb1-86d3-057516fcbbbd)

**Comment by yioannides** [comment]
I would love to have a go at this one, it's just that if the redesign is to follow GNOME HIG guidelines and modify the isometric view to top/front perspective, it'll end up looking very similar to [Gameeky](https://flathub.org/apps/dev.tchx84.Gameeky).

Thoughts, @somepaulo ?

PS. Minetest will be soon renamed to Luanti, so we also gotta keep this in mind.

**Comment by somepaulo** [comment]
This is a tough one. Will explore a way of transforming it. Maybe use Gameekey and change it to resemble this.

**Comment by yioannides** [comment]
How about this one, @somepaulo ?

![minetest](https://github.com/user-attachments/assets/80d3c3c3-e2d5-4f01-a8d6-3c8d6d5460e4)

While it does look very aesthetically pleasing and GNOME-like, I just feel it's too similar to Gameeky. I also experimented with cubing the lake, cacti and trees and using pixel gradients instead of radial gradients, but then it ceases to look like GNOME. Feel free to also experiment with this icon.

**Comment by somepaulo** [comment]
That looks very nice. Can you make a PR for it?

**Comment by yioannides** [comment]
Of course, as soon as I also create a symbolic icon for it.

**Comment by somepaulo** [comment]
Didn't think of a symbolic one, and can't really imagine how it should look like...
