### ISSUE TITLE
MoreWaita breaks Window Controls/Decorations for QT apps in Fedora 39 (Wayland)

### ISSUE THREAD

**Issue by LSeelig** [somepaulo/MoreWaita#124]
Adwaita icons enabled in gnome tweaks:
![Screenshot from 2023-11-16 20-13-59](https://github.com/somepaulo/MoreWaita/assets/37001137/cd2fc813-7bb8-4525-8e8a-8afc22e6df6a)

Morewaita icons enabled in gnome tweaks:
![Screenshot from 2023-11-16 20-13-24](https://github.com/somepaulo/MoreWaita/assets/37001137/9f68b75f-cb19-4c9b-89c7-99d854c87c91)

This isn't necessarily solely morewaita's fault. Fedora Workstation now ships [QAdwaitaDecorations](https://github.com/FedoraQt/QAdwaitaDecorations), though they usually work well. With it manually disabled or uninstalled, window decorations simply revert to their default qt look, which is even more jarring. This occurs with and without extensions, with the theme installed system-wide, user-wide, or via copr, but decorations do not change/break until the app in question is restarted. In general, situation with QT theming on GNOME is messy at best. Don't even get me started on flatpaks.

**Comment by somepaulo** [comment]
This might be related to #17.
Basically, some apps call for icons differently than Gnome Shell expects, and all sorts of weird stuff happens.  
The icons themselves in your app don't change, just the colour. I don't know where to dig for that. Maybe ask the app devs? Or maybe use BlackBox terminal )) ?

**Comment by LSeelig** [comment]
> This might be related to #17. Basically, some apps call for icons differently than Gnome Shell expects, and all sorts of weird stuff happens. The icons themselves in your app don't change, just the colour. I don't know where to dig for that. Maybe ask the app devs? Or maybe use BlackBox terminal )) ?

I'll raise an issue in the [QAdwaitaDecorations](https://github.com/FedoraQt/QAdwaitaDecorations) repo.

**Comment by somepaulo** [comment]
Is this still an issue?

**Comment by LSeelig** [comment]
Yes, but I don't currently have the time to deal with this, and at least for Flatpaks, there is a dependency issue. I don't think this issue is on Morewaita's end. If you want to close this, feel free, and I will reopen if the situation changes/I rule out other causes.

**Comment by somepaulo** [comment]
Thanks!
I'll close this for now, but do feel free to reopen if you find anything that can be done on my end.
Best of luck!

**Comment by LSeelig** [comment]
It might be worth reopening this. I still don't fully understand why this happens, and it is partially fixed. It still only affects flatpaks, and only some flatpaks at that. But it is isolated to MoreWaita. Switching my system theme to Adwaita fixes the issue fully.

**Comment by nvkomata** [comment]
this happens when the application is using or falling back to the breeze icon theme and qadwaitadecorations tries to use the application's icon theme i'm pretty sure

it's a qadwaitadecorations issue

**Comment by somepaulo** [comment]
> it's a qadwaitadecorations issue

I guess so. MoreWaita explicitly inherits only Adwaita, which, in turn, inherits hicolor and, since recently, also Adwaita Legacy.

Hicolor exists by default. That's where installed apps put their icons into. Adwaita and Adwaita Legacy should be installed (by default on Gnome).

Last time I checked, there were some issues upstream with how this inheritance mechanism works, leading to some icons not being picked up from inherited themes, but the exact cause and its location within a particular package remain undiscovered.

The only workaround for now, as far as I know, is adding the "missing" icons to MoreWaita, which I don't think is feasible because it would require extra maintenance keeping up with upstream and tracking particular "broken" icons, and I don't have time for this.

PS
I only have two Qt apps on my Arch/Gnome system (with qadwaitadecorations installed), and their icons all seem to work just fine.
