### ISSUE TITLE
Icon request: R mime

### ISSUE THREAD

**Issue by erlefloch** [somepaulo/MoreWaita#150]
### Name of app

R files (ending in ".r" or ".R")

### Link to official icon

https://www.r-project.org/logo/

### Optional image of the app icon

https://commons.wikimedia.org/wiki/File:R_logo.svg

**Comment by somepaulo** [comment]
This has been in the theme for a while. Just added a new symlink now. I don't have any `.r` files to test, but if yours are not using the icon, this means your system registers those files under a different mimetype name. You cah check `/etc/mime.types` for any additional names ad reopen this issue if you find a name not present in MoreWaita (and, by extension, in Papirus too, since I use all the same names they do).
