### ISSUE TITLE
Some mime icons stopped working since Gnome 46

### ISSUE THREAD

**Issue by fiftydinar** [somepaulo/MoreWaita#154]
Non-working mime icons are:
- .iso
- .yaml (.yml)

I will report if some other icons are not working too.

Other icons are working.

I use git version of icon pack, so I'm on latest commit version.

**Comment by somepaulo** [comment]
Just tested this, and it happens with other icon themes too, namely Papirus.
The icon being used for ISOs is the `x-content-blank-cd/bd/dvd/hddvd` one instead of `application-x-cd-image` or `application-x-iso` as it should. The regular `text-plain` icon is being used instead of `application-x-yaml`.

Digging deeper. Any pointers appreciated.

**Comment by somepaulo** [comment]
OK. Looking for system mime definitions, I found the `/usr/share/mime/` folder. Based on the `/usr/share/mime/types` file (which doesn't belong to any package on my system, btw) and on `/usr/share/mime/packages/freedesktop.org.xml`, I added three more different mimetype symlinks for `.yaml` files. One of them ended up working for me - `application-yaml`.

Digging further on `.iso` mimes.

**Comment by somepaulo** [comment]
Using the same process as above, I found a few more possible mimetype names for `.iso` files and added them one by one.
`application-vnd.efi.iso` did the trick. Marking as solved. Please open new issues if you find any other broken mimetypes.

**Comment by fiftydinar** [comment]
I confirm that the issue is fixed
