### ISSUE TITLE
Icon request: Geo Files

### ISSUE THREAD

**Issue by mfbehrens** [somepaulo/MoreWaita#213]
### Name of app

Geo mime types

### Link to official icon

N/A

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

N/A

### Additional context

I have a lot of .gpx files on my pc, and it would be nice to have an icon for those. They are not related to a special program (I am sorry for filling this template like this).

List of extension that would apply to this icon:
- `.gpx`
- `.geojson`
- `.geotiff`
- `.shp`, `.shx`
- `.qlr`
- `.qms`

Something like [that](https://www.iconfinder.com/icons/285662/map_icon) would not fit into the theme of MoreWaita but contains some important file types I would associate with these extensions

**Comment by somepaulo** [comment]
`.geotiff` is seen like a regular tiff by the system. It doesn't have a unique descriptor of its own to differentiate from a regular `.tiff`. Cahnging it would require changing the image icon affecting everything identified as a `.tiff`. Nothing I can do about it. Sorry.

Couldn't find any info on `.qms`. What do those files show in the _Properties_ dialog?

All the others and more similar mimetypes are done.

**Comment by somepaulo** [comment]
I'll close this for now, but feel free to reopen if you get a mime definition for `.qms`

**Comment by atenie** [comment]
Hi, bumping this thread for a quick fix. First, many thanks for this project.

I'd add `.gpkg` to the list. Maybe even `.prj`, but I suspect `.prj` is used by other formats as well. My extension to this thread idea is to use the already existing icon for `.qgz`, `.kmz` and `.geojson`. I haven't used `.qms`.

This is what Morewaita looks rights now with `.prj`, `.shx`, `.shp`, and `.qgz`. It's the QGIS icon that's a bit of a nuisance and coming from the GTK2 (?) era. 

Maybe replacing that particular QGIS file icon is the easiest fix since it's the biggest culprit, QGIS being the biggest GIS data tool out there for Linux.

<img width="1629" height="266" alt="Image" src="https://github.com/user-attachments/assets/2dbc9f77-0e76-45f3-b163-77757ca846aa" />
