### ISSUE TITLE
Icon request: Lazarus

### ISSUE THREAD

**Issue by vmaskmovps** [somepaulo/MoreWaita#220]
### Name of app

Lazarus

### Link to official icon

https://wiki.freepascal.org/images/f/fd/Lazarus-icons-lpr-proposal-bpsoftware.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

lazarus (not packaged as Flatpak, so that's not not applicable)

### Optional image of the app icon

![image](https://github.com/user-attachments/assets/d11fbc98-97e0-44f1-aebc-7c99b39eef56)

Here's a SVG version:
![mainicon](https://github.com/user-attachments/assets/0aea25be-8d8e-4552-8dba-74c8e07d71d0)

### Additional context

An alternate icon exists for Lazarus (which can be seen on the Lazarus page at https://www.lazarus-ide.org/), which consists of a black paw on a white background. The paw is:
![image](https://github.com/user-attachments/assets/cf642b8a-a5f5-487f-bd7e-7bc7c377b438)
and the logo on the website is:
![image](https://github.com/user-attachments/assets/c24d015a-2be9-47a9-85aa-f2e23a777c42)

I don't mind having either version (the cheetah one or the paw one), but officially it ships with the cheetah version. Can this theme support alternate icons for apps?

**Comment by somepaulo** [comment]
Some non-flatpak apps also adopt the icon naming convention, and icon names for the same app can differ from distro to distro.

No theme can do alternative icons automatically since the icon's file name is what matters. It's what is referenced in the app's `.desktop` file. Any alternative icon would have to be set manually or with a script.

I have quite a backlog of icon requests, and I'm working on it from oldest to newest, so it'll take a couple of weeks to get to this one, but I'll do it.

**Comment by vmaskmovps** [comment]
> I have quite a backlog of icon requests, and I'm working on it from oldest to newest, so it'll take a couple of weeks to get to this one, but I'll do it.

I can try and make a PR for this one, since it seems simple enough to do (same with the other issues, although LazPaint is trickier to do). If I can't do it for whatever reason or I need some advice, I'll ping you in the respective issues.

**Comment by somepaulo** [comment]
Done
