### ISSUE TITLE
Icon request: BoxBuddy

### ISSUE THREAD

**Issue by aph11** [somepaulo/MoreWaita#245]
### Name of app, mime type or folder

BoxBuddy

### Link to official icon

https://github.com/Dvlv/BoxBuddyRS/blob/master/icons/io.github.dvlv.boxbuddyrs.svg

### Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).

io.github.dvlv.boxbuddyrs

### Optional image of the icon

![io github dvlv boxbuddyrs](https://github.com/user-attachments/assets/5d0a4792-1dea-4ed4-ac53-e78ea3e82ee1)

**Comment by yioannides** [comment]
@somepaulo , how about this?

![boxbuddy1](https://github.com/user-attachments/assets/ab1b4d72-75bd-4d05-b90e-066b44511710)

**Comment by yioannides** [comment]
@polyjitter Thank you for the feedback! re: version 2, unfortunately the HIG guidelines are such that an icon's bottom perspective needs to serve as a definitive baseline / margin for the icon, so open flaps or any form of protrusion won't work. The gradient and middle dark line could be improved though. Otherwise, we could just give version 1 the face depth of version 2 (top perspective is also part of HIG's guidelines, a bit more loosely enforced though)

As for isometric icons, Morewaita tries to be as faithful to upstream as possible, so we tend to rework isometric icons onto Adwaita's style, but there are some rare cases (like [Endless Sky's icon](https://github.com/somepaulo/MoreWaita/blob/594f53f935a05b005b7be6ec367c877f4d66d201/scalable/apps/endless-sky.svg#L4)) where the upstream icon is so far out of Adwaita's style that we instead have to work around these constraints.

But in the end of the day, I'm just a frequent contributor here and not a member of Morewaita, so I don't really have a say in what gets merged or not!

**Comment by somepaulo** [comment]
I'd use file-roller as base and try to keep the flaps on top and the face on the side

**Comment by somepaulo** [comment]
Done
