### ISSUE TITLE
Make Anki icon depth color black instead of blueish

### ISSUE THREAD

**Issue by k-kirill** [somepaulo/MoreWaita#269]
Please can you make Anki icon depth color black like in https://github.com/grungefox/AdwaitaX-icon-theme?
<img src="https://raw.githubusercontent.com/grungefox/AdwaitaX-icon-theme/refs/heads/main/scalable/apps/net.ankiweb.Anki.svg" width="200">
instead of the current blueish color added in #174:
<img src="https://raw.githubusercontent.com/somepaulo/MoreWaita/refs/heads/main/scalable/apps/anki.svg" width="200">
because if all the flashcards have a black border then stacking them in a deck you will still get black depth color and not blueish.

P.S. Also it would be nice to make it bigger like the Files icon and the first Anki icon referenced above.

Thanks!

**Comment by somepaulo** [comment]
Are you referring to the shine on the corners that all Adwaita icons have? It can't be black because the main colour is black, so the shine has to be done in a shade of white or a colour. The shine isn't going anywhere, it's one of the main characteristic features of the Adwaita style. I don't like how white shine looks ot dark backgrounds, so I'm keeping the shine blue in this one.

The size is dictated by other icons of the same shape in Adwaita. So that's not changing either unless Adwaita or Anki's original icon change.

**Comment by k-kirill** [comment]
Just to show how these two icons look in my dock so that I had to replace the icon due to its shine in the corners that is just few very bright pixels which look like a defect in the icon:
![my_dock](https://github.com/user-attachments/assets/64f970ac-4cb1-429a-a87c-047ec0afa5c9)

**Comment by somepaulo** [comment]
Did what I could.

**Comment by k-kirill** [comment]
Same here as I've already found a suitable replacement and just wanted to help others. Thanks.
