### ISSUE TITLE
Jetbrains IDEs issue

### ISSUE THREAD

**Issue by Arbee4ever** [somepaulo/MoreWaita#99]
Hey, I'm on Fedora 39 (Prerelease) and it looks like all IntelliJ IDEs don't get the right icon... I've installed them using Toolbox and they all refer to an icon without the jetbrains- prefix, but simply removing that in MoreWaita's files didn't fix it... Since I don't really know how icon themes work on Fedora I don't know what to do...

**Comment by somepaulo** [comment]
Can you check the `.desktop` files for your installed JetBrains apps (typically in `/usr/share/applications/` or `~/.local/share/applications/`) and post the `Icon` line values here please?

**Comment by Arbee4ever** [comment]
Toolbox: `Icon=/home/arbee/.local/share/JetBrains/Toolbox/toolbox.svg`
IntelliJ: `Icon=/home/arbee/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/bin/idea.svg`
Webstorm: `Icon=/home/arbee/.local/share/JetBrains/Toolbox/apps/webstorm/bin/webstorm.svg`

**Comment by somepaulo** [comment]
The problem is that absolute paths are given in your `.desktop` files. No theme will work on this JetBrains installation. In order to theme it you need copies of the respective ``.desktop` files in your `~/.local/share/applications/` folder that you'd modify to only contain the icon name with no path and no extension, e.g. `toolbox`, `idea`, `webstorm`. I've added the missing symlinks in git, so make sure to update the theme for `toolbox` and `idea` to work. Let us know how it goes.

**Comment by somepaulo** [comment]
Since I haven't heard back from you, I'm assuming this issue is fixed. Feel free to reopen if you still experiencing problems.
